version: '3'
services:
  web:
    build: .
    env_file:
      - container.env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:latest"
    ports: 
      - "27018:27018"