version: '3'
services:
  web:
    build: .
    env_file:
      - container.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  mongo:
    image: "mongo:latest"
    ports: 
      - "27018:27018"